import { TemplateModule } from '../models/template';

export const NextjsTemplate: TemplateModule = {
  name: 'Next.js',
  dependencies: ['react', 'react-dom', 'next'],
  devDependencies: ['typescript', '@types/node', '@types/react', '@types/react-dom', 'tailwindcss', 'postcss', 'autoprefixer'],
  files: [
    {
      path: 'app/page.tsx',
      content: `export default function Home() {\n  return (\n    <main className="flex min-h-screen flex-col items-center justify-between p-24">\n      <h1 className="text-4xl font-bold">Welcome to ArchEngine Next.js</h1>\n    </main>\n  );\n}`,
      reason: 'Main landing page utilizing Next.js App Router and Tailwind.'
    },
    {
      path: 'app/layout.tsx',
      content: `import './globals.css';\n\nexport const metadata = {\n  title: 'ArchEngine Generated App',\n  description: 'Generated by ArchEngine Architecture Engine',\n};\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}`,
      reason: 'Root layout component for global styles and metadata.'
    },
    {
      path: 'app/globals.css',
      content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;`,
      reason: 'Global stylesheet importing Tailwind CSS directives.'
    },
    {
      path: 'tailwind.config.ts',
      content: `import type { Config } from 'tailwindcss';\n\nconst config: Config = {\n  content: [\n    './pages/**/*.{js,ts,jsx,tsx,mdx}',\n    './components/**/*.{js,ts,jsx,tsx,mdx}',\n    './app/**/*.{js,ts,jsx,tsx,mdx}',\n  ],\n  theme: {\n    extend: {},\n  },\n  plugins: [],\n};\nexport default config;`,
      reason: 'Tailwind CSS configuration file.'
    }
  ],
  architectureAdvice: `
### Next.js App Router Architecture
- **Design Pattern**: We use the new Next.js App Router (\`app/\` directory). This shifts the paradigm to Server Components by default, improving initial load times and SEO.
- **Scalability**: For global scale, deploy this application to Vercel or a CDN-backed edge network. Use Next.js caching and revalidation strategies (ISR) to minimize database hits.
- **Security**: Be careful not to leak secrets to the client. Any environment variable that does not start with \`NEXT_PUBLIC_\` is safely hidden on the server.
`
};
