import { Logger } from '../services/logger';
import { ProjectIntent } from '../models/blueprint';
import { SettingsService } from '../services/settings';
import { TemplateRegistry } from './templateRegistry';

export class AdvisorEngine {
  public async generateAdvice(intent: ProjectIntent): Promise<string> {
    Logger.info('AdvisorEngine generating architecture advice...');
    
    const geminiKey = SettingsService.getApiKey('gemini');
    
    if (geminiKey && geminiKey.trim() !== '') {
      Logger.info('Using LLM (Gemini) for architectural advice...');
      try {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${geminiKey}`;
        const prompt = `As a Senior Software Architect, generate an ARCHITECTURE.md for a project with the following specs: Type: ${intent.projectType}, Framework: ${intent.framework}, Database: ${intent.database || 'None'}, Features: ${intent.features.join(', ')}. Include sections on Design Patterns, Scalability, and Security. Use markdown formatting.`;
        
        const payload = { contents: [{ parts: [{ text: prompt }] }] };
        const response = await fetch(url, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload)
        });

        if (response.ok) {
          const data = await response.json() as any;
          return data.candidates[0].content.parts[0].text;
        }
      } catch (err) {
        Logger.warn('Gemini Advisor failed, falling back to Pure Logic Advisor...');
      }
    }

    Logger.info('Using Pure Logic (Templates) for architectural advice...');
    let advice = `# Project Architecture Guide\n\nGenerated by ArchEngine.\n\n`;
    
    const frameworkModule = TemplateRegistry.getFramework(intent.framework);
    if (frameworkModule && frameworkModule.architectureAdvice) {
      advice += frameworkModule.architectureAdvice + '\\n';
    }

    if (intent.database) {
      const dbModule = TemplateRegistry.getDatabase(intent.database);
      if (dbModule && dbModule.architectureAdvice) {
        advice += dbModule.architectureAdvice + '\\n';
      }
    }

    // Default fallback if no advice found
    if (advice.length < 100) {
      advice += `### General Advice\n- **Structure**: Keep your code modular.\n- **Security**: Never commit secrets to Git.\n`;
    }

    return advice;
  }
}
