import { Logger } from '../services/logger';
import { ProjectIntent } from '../models/blueprint';
import { SettingsService } from '../services/settings';
import { TemplateRegistry } from './templateRegistry';
import * as https from 'https';

export class AdvisorEngine {
  public async generateAdvice(intent: ProjectIntent): Promise<string> {
    Logger.info('AdvisorEngine generating architecture advice...');
    
    const geminiKey = SettingsService.getApiKey('gemini');
    
    if (geminiKey && geminiKey.trim() !== '') {
      Logger.info('Using LLM (Gemini) for architectural advice...');
      try {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${geminiKey}`;
        const prompt = `As a Senior Software Architect, generate an ARCHITECTURE.md for a project with the following specs: Type: ${intent.projectType}, Framework: ${intent.framework}, Database: ${intent.database || 'None'}, Features: ${intent.features.join(', ')}. Include sections on Design Patterns, Scalability, and Security. Use markdown formatting.`;
        
        const payload = { contents: [{ parts: [{ text: prompt }] }] };
        
        const data = await new Promise<any>((resolve, reject) => {
          const payloadString = JSON.stringify(payload);
          const req = https.request(url, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Content-Length': Buffer.byteLength(payloadString)
            }
          }, (res) => {
            let body = '';
            res.on('data', chunk => body += chunk);
            res.on('end', () => {
              if (res.statusCode && res.statusCode >= 200 && res.statusCode < 300) {
                resolve(JSON.parse(body));
              } else {
                reject(new Error(`API error: ${res.statusCode} ${res.statusMessage}`));
              }
            });
          });
          req.on('error', reject);
          req.write(payloadString);
          req.end();
        });

        return data.candidates[0].content.parts[0].text;
      } catch (err) {
        Logger.warn('Gemini Advisor failed, falling back to Pure Logic Advisor...');
      }
    }

    Logger.info('Using Pure Logic (Templates) for architectural advice...');
    let advice = `# Project Architecture Guide\n\nGenerated by ArchEngine.\n\n`;
    
    const frameworkModule = TemplateRegistry.getFramework(intent.framework);
    if (frameworkModule && frameworkModule.architectureAdvice) {
      advice += frameworkModule.architectureAdvice + '\\n';
    }

    if (intent.database) {
      const dbModule = TemplateRegistry.getDatabase(intent.database);
      if (dbModule && dbModule.architectureAdvice) {
        advice += dbModule.architectureAdvice + '\\n';
      }
    }

    // Default fallback if no advice found
    if (advice.length < 100) {
      advice += `### General Advice\n- **Structure**: Keep your code modular.\n- **Security**: Never commit secrets to Git.\n`;
    }

    return advice;
  }
}
