import * as vscode from 'vscode';
import * as path from 'path';
import { promises as fs } from 'fs';
import { SessionEngine } from './sessionEngine';
import { NotesEngine } from './notesEngine';
import { Logger } from '../services/logger';
import { ContextEngine } from './contextEngine';

export class ResumeGenerator {
  public async generateResume(rootPath: string): Promise<void> {
    const sessionEngine = new SessionEngine();
    const notesEngine = new NotesEngine();
    const contextEngine = new ContextEngine();

    const context = await contextEngine.analyzeWorkspace();
    const totalMinutes = await sessionEngine.getTotalTime(rootPath);
    const notes = await notesEngine.getNotes(rootPath);

    let resume = `# Developer Case Study\n\n`;
    resume += `**Generated by ArchEngine Memory System**\n\n`;

    resume += `## 🛠 Tech Stack\n`;
    resume += `- **Framework:** ${context.existingFramework || 'Custom/Unknown'}\n`;
    resume += `- **Core Dependencies:** ${context.existingDependencies.slice(0, 10).join(', ')}\n\n`;

    resume += `## ⏱ Time Investment\n`;
    resume += `- **Total Active Development Time:** ${totalMinutes} minutes\n\n`;

    resume += `## 🚀 Challenges & Solutions\n`;
    if (notes.length === 0) {
      resume += `*No blockers logged during this project lifecycle.*\n`;
    } else {
      notes.forEach((note, index) => {
        const date = new Date(note.timestamp).toLocaleDateString();
        resume += `### Challenge ${index + 1} (${date})\n`;
        resume += `> ${note.content}\n\n`;
      });
    }

    const outputPath = path.join(rootPath, 'PROJECT_CASE_STUDY.md');
    await fs.writeFile(outputPath, resume, 'utf8');

    Logger.info('Developer Resume (Case Study) generated successfully.');
    vscode.window.showInformationMessage('ArchEngine: PROJECT_CASE_STUDY.md generated!');
  }
}
